---
- name: AS3
  hosts: f5
  connection: httpapi
  gather_facts: false
  collections:
    - f5networks.f5_bigip

  # Connection Info
  vars:
    ansible_host: 10.1.1.245
    ansible_user: admin
    ansible_httpapi_password: admin
    ansible_httpapi_port: 443
    ansible_network_os: f5networks.f5_bigip.bigip
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no

  tasks:

    - name: Remove one tenant - AS3
      bigip_as3_deploy:
        tenant: Sample_01
        state: absent

